apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      role: myrole
  template:
    metadata:
      labels:
        app: nginx
        role: myrole
    spec:
      containers:
      - name: moncontainer
        image: 435606335423.dkr.ecr.eu-west-1.amazonaws.com/alejandro-apache:1.0.1
        ports:
        - containerPort: 80