apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: alejandro-ns
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: 435606335423.dkr.ecr.eu-west-1.amazonaws.com/alejandro-apache:1.0.1
      ports:
        - name: web
          containerPort: 80
          protocol: TCP