apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: alejandro-ns    
spec:
  selector:
    role: myrole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
